import { ArrowUpRight, ArrowDown, MapPin, Compass } from 'lucide-react';
const demo = 'https://colejorgensen28-jobfinder-mvp-streamlit-app-y5bg8r.streamlit.app/';
const stories = [
  { number: '03', category: 'GIS ANALYSIS / URBAN PLANNING', title: 'Knoxville’s Urban Growth Based on Terrain', description: 'Exploring how slope, road access, existing development, and environmental constraints shape where Knoxville can grow. A terrain-based housing suitability analysis built in ArcGIS Pro.', image: '/images/knoxville.jpg', alt: 'Housing suitability map of Knoxville and surrounding terrain', url: 'https://storymaps.arcgis.com/stories/38c29a40909d4fcd8070e5e6805f54a2', tags: ['ArcGIS Pro', 'Suitability modeling', 'StoryMaps'] },
  { number: '04', category: 'GEOGRAPHIC STORYTELLING / WILDLIFE', title: 'The Everglade Snail Kite', description: 'A story map introducing an endangered bird in Florida, its wetland habitat, and its specialized relationship with apple snails.', image: '/images/snail-kite.jpg', alt: 'Everglade snail kite pictured in the original story map', url: 'https://storymaps.arcgis.com/stories/651b5e42fbf14de0bf85e3101c221870', tags: ['ArcGIS StoryMaps', 'Wildlife', 'Florida'] },
];
export default function Home() {
 return <>
  <a className="skip-link" href="#work">Skip to selected work</a>
  <header className="header wrap"><a href="#" className="identity" aria-label="Cole Jorgensen home"><span className="monogram">CJ<span>↗</span></span><span>Cole Jorgensen</span></a><nav aria-label="Main navigation"><a href="#about">About me</a><a href="#work">Selected work</a><a href="https://github.com/colejorgensen28" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a></nav></header>
  <main>
  <section id="about" className="about wrap" aria-labelledby="about-title">
    <div className="about-photo"><img src="/images/cole-jorgensen.jpeg" alt="Cole Jorgensen wearing a dark suit and tie" width={3024} height={4032} loading="eager" fetchPriority="high" /></div>
    <div className="about-copy"><div className="eyebrow">BEHIND THE PROJECTS</div><h2 id="about-title">About me</h2><p className="about-lead">I’m Cole Jorgensen. I bring maps, data, and application development together to explore how people connect with places.</p><p>My work spans GIS analysis, interactive storytelling, and practical web applications. Through projects like JobFinder and Church Atlas, I explore how location can help people find opportunities and communities.</p><p>I also use ArcGIS StoryMaps to communicate geographic and environmental topics, from terrain and housing growth in Knoxville to the Everglade snail kite in Florida.</p><div className="tags"><span>Geographic information systems</span><span>Web applications</span><span>Interactive storytelling</span></div></div>
  </section>
  <section className="intro wrap" aria-labelledby="intro-title"><div className="eyebrow"><span className="dot"/> GIS · APPLICATIONS · STORYTELLING</div><h1 id="intro-title">A sense of place.<br/><span>A world of possibility.</span></h1><div className="intro-bottom"><p>I’m Cole Jorgensen. I use maps, data, and software to explore places and build useful tools.</p><a className="work-link" href="#work">Explore my work <ArrowDown size={20}/></a></div></section>
  <section id="work" className="work wrap" aria-labelledby="work-title"><div className="section-heading"><h2 id="work-title">Selected work</h2><span>01 — 04</span></div>
  <article className="featured"><div className="feature-copy"><div className="eyebrow">01 / APPLICATION PROTOTYPE</div><h3>JobFinder<span className="title-dot">.</span></h3><p className="lead">The job search, with location in focus.</p><p>Explore jobs on a map, narrow your search with detailed filters, and compare opportunities with commute and job-fit information.</p><div className="tags"><span>Python</span><span>Streamlit</span><span>GIS</span></div><a className="primary-link" href={demo} target="_blank" rel="noreferrer">Open app demo <ArrowUpRight size={19}/></a><p className="demo-note">Prototype with demonstration data. Opens on Streamlit.</p></div><div className="feature-index" aria-label="JobFinder features"><div className="feature-top"><Compass size={28}/><span>JOBFINDER / FIELD NOTES</span></div><div className="feature-word">Find your<br/>next <em>place.</em></div><ul><li><span>01</span> Discover jobs by location <MapPin size={18}/></li><li><span>02</span> Filter what matters <ArrowUpRight size={18}/></li><li><span>03</span> Compare your commute <ArrowUpRight size={18}/></li></ul><span className="feature-caption">A GIS-based job finding application</span></div></article>
  <article className="church-feature" aria-labelledby="church-title"><div><div className="eyebrow">02 / APPLICATION PROTOTYPE</div><h3 id="church-title">Church Atlas</h3><p>A map-based church finder with denomination and belief filters, service times, and practical visit needs. Compare matches, save favorites, and plan a route between churches.</p><div className="tags"><span>JavaScript</span><span>Leaflet</span><span>GIS</span></div></div><div className="church-action"><a className="primary-link" href="/church-atlas/">Open app demo <ArrowUpRight size={19}/></a><p>Interactive prototype with sample listings.</p></div></article>
  <div className="story-grid">{stories.map(story => <article className="story-card" key={story.number}><a className="story-image" href={story.url} target="_blank" rel="noreferrer" aria-label={`Read ${story.title}`}><img src={story.image} alt={story.alt} width={640} height={425} loading="lazy"/><span className="image-arrow"><ArrowUpRight size={22}/></span></a><div className="story-content"><div className="eyebrow">{story.number} / {story.category}</div><h3><a href={story.url} target="_blank" rel="noreferrer">{story.title}</a></h3><p>{story.description}</p><div className="tags">{story.tags.map(tag => <span key={tag}>{tag}</span>)}</div><a className="text-link" href={story.url} target="_blank" rel="noreferrer">Explore story map <ArrowUpRight size={18}/></a></div></article>)}</div></section>
  </main>
  <footer className="footer wrap"><div><strong>Cole Jorgensen</strong><p>Maps, software, and stories.</p></div><a href="https://github.com/colejorgensen28" target="_blank" rel="noreferrer">Find me on GitHub <ArrowUpRight size={17}/></a></footer>
 </>;
}




